### PR TITLE
fix: bcs-logbeat-sidecar hangs forever. fix #883

### LINKED ISSUE #883: [bug] bcs-logbeat-sidecar inspect 容器永久阻塞
问题描述
===========
部分开启 `shareProcessNamespace` 的容器根进程未妥善处理退出信号，或根进程执行结束后退出，导致其子进程被pause进程托管，此时对容器进行exec、inspect等操作均永久阻塞。此问题会使logbeat-sidecar永久阻塞在异常容器的inspect上，无法正常落地日志采集配置

重现方法
================
- 开启 `shareProcessNamespace` 模式
- 业务容器是多进程容器
- 业务容器根号进程退出，观察原业务容器子进程的父进程变成1号进程（一般是pause）
- 下发采集配置，采集配置不会落地，logbeat-sidecar日志仅打印容器事件，配置落地相关逻辑无日志输出

关键信息
=========

请提供以下信息:

 - [ ] bk-bcs   版本: 
 - [ ] 操作系统
 - [ ] bk-bcs 异常日志

### PR DESCRIPTION
**Pull request by AlexAi27**

### CODE REVIEW

File: bcs-services/bcs-logbeat-sidecar/sidecar/cache.go [hunk 1]
```diff
@@ -0,0 +1,96 @@
...
+
+	"github.com/Tencent/bk-bcs/bcs-common/common/blog"
+	docker "github.com/fsouza/go-dockerclient"
+)
+
+func (s *SidecarController) syncContainerCache() {
+	s.syncContainerCacheOnce()
+	go func() {
+		blog.Infof("Start sync containerInfoCache periodly")
+		ticker := time.NewTicker(time.Hour)
```
Comment (DeveloperJim) [inline bcs-services/bcs-logbeat-sidecar/sidecar/cache.go:28]: 良好习惯，保障ticker正常退出后stop

**Review by DeveloperJim — CHANGES_REQUESTED** [review]

**Review by DeveloperJim — APPROVED** [review]
LGTM
